[package]
name = "markdown-to-diouxs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { path = "../../dioxus", features = ["ssr", "web"] }
pulldown-cmark = "0.8.0"
